/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedSystemIndexRouteImport } from './routes/_authenticated/system/index'
import { Route as AuthenticatedMesIndexRouteImport } from './routes/_authenticated/mes/index'
import { Route as AuthenticatedSystemUserManagementRouteImport } from './routes/_authenticated/system/user-management'
import { Route as AuthenticatedSystemTestUploadRouteImport } from './routes/_authenticated/system/test-upload'
import { Route as AuthenticatedSystemSettingsRouteImport } from './routes/_authenticated/system/settings'
import { Route as AuthenticatedSystemRoleManagementRouteImport } from './routes/_authenticated/system/role-management'
import { Route as AuthenticatedSystemIntegrationsRouteImport } from './routes/_authenticated/system/integrations'
import { Route as AuthenticatedSystemAuditLogsRouteImport } from './routes/_authenticated/system/audit-logs'
import { Route as AuthenticatedMesWorkOrdersRouteImport } from './routes/_authenticated/mes/work-orders'
import { Route as AuthenticatedMesTraceRouteImport } from './routes/_authenticated/mes/trace'
import { Route as AuthenticatedMesRoutesRouteImport } from './routes/_authenticated/mes/routes'
import { Route as AuthenticatedMesRouteVersionsRouteImport } from './routes/_authenticated/mes/route-versions'
import { Route as AuthenticatedMesReworkTasksRouteImport } from './routes/_authenticated/mes/rework-tasks'
import { Route as AuthenticatedMesReadinessExceptionsRouteImport } from './routes/_authenticated/mes/readiness-exceptions'
import { Route as AuthenticatedMesReadinessConfigRouteImport } from './routes/_authenticated/mes/readiness-config'
import { Route as AuthenticatedMesFaiRouteImport } from './routes/_authenticated/mes/fai'
import { Route as AuthenticatedMesExecutionRouteImport } from './routes/_authenticated/mes/execution'
import { Route as AuthenticatedMesDefectsRouteImport } from './routes/_authenticated/mes/defects'
import { Route as AuthenticatedMesWorkCentersIndexRouteImport } from './routes/_authenticated/mes/work-centers/index'
import { Route as AuthenticatedMesRunsIndexRouteImport } from './routes/_authenticated/mes/runs/index'
import { Route as AuthenticatedMesRoutesIndexRouteImport } from './routes/_authenticated/mes/routes/index'
import { Route as AuthenticatedMesOqcIndexRouteImport } from './routes/_authenticated/mes/oqc/index'
import { Route as AuthenticatedMesMaterialsIndexRouteImport } from './routes/_authenticated/mes/materials/index'
import { Route as AuthenticatedMesLoadingIndexRouteImport } from './routes/_authenticated/mes/loading/index'
import { Route as AuthenticatedMesDataCollectionSpecsIndexRouteImport } from './routes/_authenticated/mes/data-collection-specs/index'
import { Route as AuthenticatedMesBomsIndexRouteImport } from './routes/_authenticated/mes/boms/index'
import { Route as AuthenticatedMesBakeRecordsIndexRouteImport } from './routes/_authenticated/mes/bake-records/index'
import { Route as AuthenticatedMesRunsRunNoRouteImport } from './routes/_authenticated/mes/runs/$runNo'
import { Route as AuthenticatedMesRoutesRoutingCodeRouteImport } from './routes/_authenticated/mes/routes/$routingCode'
import { Route as AuthenticatedMesOqcRulesRouteImport } from './routes/_authenticated/mes/oqc/rules'
import { Route as AuthenticatedMesLoadingSlotConfigRouteImport } from './routes/_authenticated/mes/loading/slot-config'
import { Route as AuthenticatedMesIntegrationStatusRouteImport } from './routes/_authenticated/mes/integration/status'
import { Route as AuthenticatedMesIntegrationManualEntryRouteImport } from './routes/_authenticated/mes/integration/manual-entry'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSystemIndexRoute =
  AuthenticatedSystemIndexRouteImport.update({
    id: '/system/',
    path: '/system/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMesIndexRoute = AuthenticatedMesIndexRouteImport.update({
  id: '/mes/',
  path: '/mes/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSystemUserManagementRoute =
  AuthenticatedSystemUserManagementRouteImport.update({
    id: '/system/user-management',
    path: '/system/user-management',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSystemTestUploadRoute =
  AuthenticatedSystemTestUploadRouteImport.update({
    id: '/system/test-upload',
    path: '/system/test-upload',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSystemSettingsRoute =
  AuthenticatedSystemSettingsRouteImport.update({
    id: '/system/settings',
    path: '/system/settings',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSystemRoleManagementRoute =
  AuthenticatedSystemRoleManagementRouteImport.update({
    id: '/system/role-management',
    path: '/system/role-management',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSystemIntegrationsRoute =
  AuthenticatedSystemIntegrationsRouteImport.update({
    id: '/system/integrations',
    path: '/system/integrations',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSystemAuditLogsRoute =
  AuthenticatedSystemAuditLogsRouteImport.update({
    id: '/system/audit-logs',
    path: '/system/audit-logs',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMesWorkOrdersRoute =
  AuthenticatedMesWorkOrdersRouteImport.update({
    id: '/mes/work-orders',
    path: '/mes/work-orders',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMesTraceRoute = AuthenticatedMesTraceRouteImport.update({
  id: '/mes/trace',
  path: '/mes/trace',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMesRoutesRoute = AuthenticatedMesRoutesRouteImport.update({
  id: '/mes/routes',
  path: '/mes/routes',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMesRouteVersionsRoute =
  AuthenticatedMesRouteVersionsRouteImport.update({
    id: '/mes/route-versions',
    path: '/mes/route-versions',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMesReworkTasksRoute =
  AuthenticatedMesReworkTasksRouteImport.update({
    id: '/mes/rework-tasks',
    path: '/mes/rework-tasks',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMesReadinessExceptionsRoute =
  AuthenticatedMesReadinessExceptionsRouteImport.update({
    id: '/mes/readiness-exceptions',
    path: '/mes/readiness-exceptions',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMesReadinessConfigRoute =
  AuthenticatedMesReadinessConfigRouteImport.update({
    id: '/mes/readiness-config',
    path: '/mes/readiness-config',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMesFaiRoute = AuthenticatedMesFaiRouteImport.update({
  id: '/mes/fai',
  path: '/mes/fai',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMesExecutionRoute =
  AuthenticatedMesExecutionRouteImport.update({
    id: '/mes/execution',
    path: '/mes/execution',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMesDefectsRoute = AuthenticatedMesDefectsRouteImport.update({
  id: '/mes/defects',
  path: '/mes/defects',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMesWorkCentersIndexRoute =
  AuthenticatedMesWorkCentersIndexRouteImport.update({
    id: '/mes/work-centers/',
    path: '/mes/work-centers/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMesRunsIndexRoute =
  AuthenticatedMesRunsIndexRouteImport.update({
    id: '/mes/runs/',
    path: '/mes/runs/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMesRoutesIndexRoute =
  AuthenticatedMesRoutesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedMesRoutesRoute,
  } as any)
const AuthenticatedMesOqcIndexRoute =
  AuthenticatedMesOqcIndexRouteImport.update({
    id: '/mes/oqc/',
    path: '/mes/oqc/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMesMaterialsIndexRoute =
  AuthenticatedMesMaterialsIndexRouteImport.update({
    id: '/mes/materials/',
    path: '/mes/materials/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMesLoadingIndexRoute =
  AuthenticatedMesLoadingIndexRouteImport.update({
    id: '/mes/loading/',
    path: '/mes/loading/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMesDataCollectionSpecsIndexRoute =
  AuthenticatedMesDataCollectionSpecsIndexRouteImport.update({
    id: '/mes/data-collection-specs/',
    path: '/mes/data-collection-specs/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMesBomsIndexRoute =
  AuthenticatedMesBomsIndexRouteImport.update({
    id: '/mes/boms/',
    path: '/mes/boms/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMesBakeRecordsIndexRoute =
  AuthenticatedMesBakeRecordsIndexRouteImport.update({
    id: '/mes/bake-records/',
    path: '/mes/bake-records/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMesRunsRunNoRoute =
  AuthenticatedMesRunsRunNoRouteImport.update({
    id: '/mes/runs/$runNo',
    path: '/mes/runs/$runNo',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMesRoutesRoutingCodeRoute =
  AuthenticatedMesRoutesRoutingCodeRouteImport.update({
    id: '/$routingCode',
    path: '/$routingCode',
    getParentRoute: () => AuthenticatedMesRoutesRoute,
  } as any)
const AuthenticatedMesOqcRulesRoute =
  AuthenticatedMesOqcRulesRouteImport.update({
    id: '/mes/oqc/rules',
    path: '/mes/oqc/rules',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMesLoadingSlotConfigRoute =
  AuthenticatedMesLoadingSlotConfigRouteImport.update({
    id: '/mes/loading/slot-config',
    path: '/mes/loading/slot-config',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMesIntegrationStatusRoute =
  AuthenticatedMesIntegrationStatusRouteImport.update({
    id: '/mes/integration/status',
    path: '/mes/integration/status',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMesIntegrationManualEntryRoute =
  AuthenticatedMesIntegrationManualEntryRouteImport.update({
    id: '/mes/integration/manual-entry',
    path: '/mes/integration/manual-entry',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/': typeof AuthenticatedIndexRoute
  '/mes/defects': typeof AuthenticatedMesDefectsRoute
  '/mes/execution': typeof AuthenticatedMesExecutionRoute
  '/mes/fai': typeof AuthenticatedMesFaiRoute
  '/mes/readiness-config': typeof AuthenticatedMesReadinessConfigRoute
  '/mes/readiness-exceptions': typeof AuthenticatedMesReadinessExceptionsRoute
  '/mes/rework-tasks': typeof AuthenticatedMesReworkTasksRoute
  '/mes/route-versions': typeof AuthenticatedMesRouteVersionsRoute
  '/mes/routes': typeof AuthenticatedMesRoutesRouteWithChildren
  '/mes/trace': typeof AuthenticatedMesTraceRoute
  '/mes/work-orders': typeof AuthenticatedMesWorkOrdersRoute
  '/system/audit-logs': typeof AuthenticatedSystemAuditLogsRoute
  '/system/integrations': typeof AuthenticatedSystemIntegrationsRoute
  '/system/role-management': typeof AuthenticatedSystemRoleManagementRoute
  '/system/settings': typeof AuthenticatedSystemSettingsRoute
  '/system/test-upload': typeof AuthenticatedSystemTestUploadRoute
  '/system/user-management': typeof AuthenticatedSystemUserManagementRoute
  '/mes': typeof AuthenticatedMesIndexRoute
  '/system': typeof AuthenticatedSystemIndexRoute
  '/mes/integration/manual-entry': typeof AuthenticatedMesIntegrationManualEntryRoute
  '/mes/integration/status': typeof AuthenticatedMesIntegrationStatusRoute
  '/mes/loading/slot-config': typeof AuthenticatedMesLoadingSlotConfigRoute
  '/mes/oqc/rules': typeof AuthenticatedMesOqcRulesRoute
  '/mes/routes/$routingCode': typeof AuthenticatedMesRoutesRoutingCodeRoute
  '/mes/runs/$runNo': typeof AuthenticatedMesRunsRunNoRoute
  '/mes/bake-records': typeof AuthenticatedMesBakeRecordsIndexRoute
  '/mes/boms': typeof AuthenticatedMesBomsIndexRoute
  '/mes/data-collection-specs': typeof AuthenticatedMesDataCollectionSpecsIndexRoute
  '/mes/loading': typeof AuthenticatedMesLoadingIndexRoute
  '/mes/materials': typeof AuthenticatedMesMaterialsIndexRoute
  '/mes/oqc': typeof AuthenticatedMesOqcIndexRoute
  '/mes/routes/': typeof AuthenticatedMesRoutesIndexRoute
  '/mes/runs': typeof AuthenticatedMesRunsIndexRoute
  '/mes/work-centers': typeof AuthenticatedMesWorkCentersIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/': typeof AuthenticatedIndexRoute
  '/mes/defects': typeof AuthenticatedMesDefectsRoute
  '/mes/execution': typeof AuthenticatedMesExecutionRoute
  '/mes/fai': typeof AuthenticatedMesFaiRoute
  '/mes/readiness-config': typeof AuthenticatedMesReadinessConfigRoute
  '/mes/readiness-exceptions': typeof AuthenticatedMesReadinessExceptionsRoute
  '/mes/rework-tasks': typeof AuthenticatedMesReworkTasksRoute
  '/mes/route-versions': typeof AuthenticatedMesRouteVersionsRoute
  '/mes/trace': typeof AuthenticatedMesTraceRoute
  '/mes/work-orders': typeof AuthenticatedMesWorkOrdersRoute
  '/system/audit-logs': typeof AuthenticatedSystemAuditLogsRoute
  '/system/integrations': typeof AuthenticatedSystemIntegrationsRoute
  '/system/role-management': typeof AuthenticatedSystemRoleManagementRoute
  '/system/settings': typeof AuthenticatedSystemSettingsRoute
  '/system/test-upload': typeof AuthenticatedSystemTestUploadRoute
  '/system/user-management': typeof AuthenticatedSystemUserManagementRoute
  '/mes': typeof AuthenticatedMesIndexRoute
  '/system': typeof AuthenticatedSystemIndexRoute
  '/mes/integration/manual-entry': typeof AuthenticatedMesIntegrationManualEntryRoute
  '/mes/integration/status': typeof AuthenticatedMesIntegrationStatusRoute
  '/mes/loading/slot-config': typeof AuthenticatedMesLoadingSlotConfigRoute
  '/mes/oqc/rules': typeof AuthenticatedMesOqcRulesRoute
  '/mes/routes/$routingCode': typeof AuthenticatedMesRoutesRoutingCodeRoute
  '/mes/runs/$runNo': typeof AuthenticatedMesRunsRunNoRoute
  '/mes/bake-records': typeof AuthenticatedMesBakeRecordsIndexRoute
  '/mes/boms': typeof AuthenticatedMesBomsIndexRoute
  '/mes/data-collection-specs': typeof AuthenticatedMesDataCollectionSpecsIndexRoute
  '/mes/loading': typeof AuthenticatedMesLoadingIndexRoute
  '/mes/materials': typeof AuthenticatedMesMaterialsIndexRoute
  '/mes/oqc': typeof AuthenticatedMesOqcIndexRoute
  '/mes/routes': typeof AuthenticatedMesRoutesIndexRoute
  '/mes/runs': typeof AuthenticatedMesRunsIndexRoute
  '/mes/work-centers': typeof AuthenticatedMesWorkCentersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/mes/defects': typeof AuthenticatedMesDefectsRoute
  '/_authenticated/mes/execution': typeof AuthenticatedMesExecutionRoute
  '/_authenticated/mes/fai': typeof AuthenticatedMesFaiRoute
  '/_authenticated/mes/readiness-config': typeof AuthenticatedMesReadinessConfigRoute
  '/_authenticated/mes/readiness-exceptions': typeof AuthenticatedMesReadinessExceptionsRoute
  '/_authenticated/mes/rework-tasks': typeof AuthenticatedMesReworkTasksRoute
  '/_authenticated/mes/route-versions': typeof AuthenticatedMesRouteVersionsRoute
  '/_authenticated/mes/routes': typeof AuthenticatedMesRoutesRouteWithChildren
  '/_authenticated/mes/trace': typeof AuthenticatedMesTraceRoute
  '/_authenticated/mes/work-orders': typeof AuthenticatedMesWorkOrdersRoute
  '/_authenticated/system/audit-logs': typeof AuthenticatedSystemAuditLogsRoute
  '/_authenticated/system/integrations': typeof AuthenticatedSystemIntegrationsRoute
  '/_authenticated/system/role-management': typeof AuthenticatedSystemRoleManagementRoute
  '/_authenticated/system/settings': typeof AuthenticatedSystemSettingsRoute
  '/_authenticated/system/test-upload': typeof AuthenticatedSystemTestUploadRoute
  '/_authenticated/system/user-management': typeof AuthenticatedSystemUserManagementRoute
  '/_authenticated/mes/': typeof AuthenticatedMesIndexRoute
  '/_authenticated/system/': typeof AuthenticatedSystemIndexRoute
  '/_authenticated/mes/integration/manual-entry': typeof AuthenticatedMesIntegrationManualEntryRoute
  '/_authenticated/mes/integration/status': typeof AuthenticatedMesIntegrationStatusRoute
  '/_authenticated/mes/loading/slot-config': typeof AuthenticatedMesLoadingSlotConfigRoute
  '/_authenticated/mes/oqc/rules': typeof AuthenticatedMesOqcRulesRoute
  '/_authenticated/mes/routes/$routingCode': typeof AuthenticatedMesRoutesRoutingCodeRoute
  '/_authenticated/mes/runs/$runNo': typeof AuthenticatedMesRunsRunNoRoute
  '/_authenticated/mes/bake-records/': typeof AuthenticatedMesBakeRecordsIndexRoute
  '/_authenticated/mes/boms/': typeof AuthenticatedMesBomsIndexRoute
  '/_authenticated/mes/data-collection-specs/': typeof AuthenticatedMesDataCollectionSpecsIndexRoute
  '/_authenticated/mes/loading/': typeof AuthenticatedMesLoadingIndexRoute
  '/_authenticated/mes/materials/': typeof AuthenticatedMesMaterialsIndexRoute
  '/_authenticated/mes/oqc/': typeof AuthenticatedMesOqcIndexRoute
  '/_authenticated/mes/routes/': typeof AuthenticatedMesRoutesIndexRoute
  '/_authenticated/mes/runs/': typeof AuthenticatedMesRunsIndexRoute
  '/_authenticated/mes/work-centers/': typeof AuthenticatedMesWorkCentersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/notifications'
    | '/profile'
    | '/'
    | '/mes/defects'
    | '/mes/execution'
    | '/mes/fai'
    | '/mes/readiness-config'
    | '/mes/readiness-exceptions'
    | '/mes/rework-tasks'
    | '/mes/route-versions'
    | '/mes/routes'
    | '/mes/trace'
    | '/mes/work-orders'
    | '/system/audit-logs'
    | '/system/integrations'
    | '/system/role-management'
    | '/system/settings'
    | '/system/test-upload'
    | '/system/user-management'
    | '/mes'
    | '/system'
    | '/mes/integration/manual-entry'
    | '/mes/integration/status'
    | '/mes/loading/slot-config'
    | '/mes/oqc/rules'
    | '/mes/routes/$routingCode'
    | '/mes/runs/$runNo'
    | '/mes/bake-records'
    | '/mes/boms'
    | '/mes/data-collection-specs'
    | '/mes/loading'
    | '/mes/materials'
    | '/mes/oqc'
    | '/mes/routes/'
    | '/mes/runs'
    | '/mes/work-centers'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/notifications'
    | '/profile'
    | '/'
    | '/mes/defects'
    | '/mes/execution'
    | '/mes/fai'
    | '/mes/readiness-config'
    | '/mes/readiness-exceptions'
    | '/mes/rework-tasks'
    | '/mes/route-versions'
    | '/mes/trace'
    | '/mes/work-orders'
    | '/system/audit-logs'
    | '/system/integrations'
    | '/system/role-management'
    | '/system/settings'
    | '/system/test-upload'
    | '/system/user-management'
    | '/mes'
    | '/system'
    | '/mes/integration/manual-entry'
    | '/mes/integration/status'
    | '/mes/loading/slot-config'
    | '/mes/oqc/rules'
    | '/mes/routes/$routingCode'
    | '/mes/runs/$runNo'
    | '/mes/bake-records'
    | '/mes/boms'
    | '/mes/data-collection-specs'
    | '/mes/loading'
    | '/mes/materials'
    | '/mes/oqc'
    | '/mes/routes'
    | '/mes/runs'
    | '/mes/work-centers'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/notifications'
    | '/_authenticated/profile'
    | '/_authenticated/'
    | '/_authenticated/mes/defects'
    | '/_authenticated/mes/execution'
    | '/_authenticated/mes/fai'
    | '/_authenticated/mes/readiness-config'
    | '/_authenticated/mes/readiness-exceptions'
    | '/_authenticated/mes/rework-tasks'
    | '/_authenticated/mes/route-versions'
    | '/_authenticated/mes/routes'
    | '/_authenticated/mes/trace'
    | '/_authenticated/mes/work-orders'
    | '/_authenticated/system/audit-logs'
    | '/_authenticated/system/integrations'
    | '/_authenticated/system/role-management'
    | '/_authenticated/system/settings'
    | '/_authenticated/system/test-upload'
    | '/_authenticated/system/user-management'
    | '/_authenticated/mes/'
    | '/_authenticated/system/'
    | '/_authenticated/mes/integration/manual-entry'
    | '/_authenticated/mes/integration/status'
    | '/_authenticated/mes/loading/slot-config'
    | '/_authenticated/mes/oqc/rules'
    | '/_authenticated/mes/routes/$routingCode'
    | '/_authenticated/mes/runs/$runNo'
    | '/_authenticated/mes/bake-records/'
    | '/_authenticated/mes/boms/'
    | '/_authenticated/mes/data-collection-specs/'
    | '/_authenticated/mes/loading/'
    | '/_authenticated/mes/materials/'
    | '/_authenticated/mes/oqc/'
    | '/_authenticated/mes/routes/'
    | '/_authenticated/mes/runs/'
    | '/_authenticated/mes/work-centers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/system/': {
      id: '/_authenticated/system/'
      path: '/system'
      fullPath: '/system'
      preLoaderRoute: typeof AuthenticatedSystemIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/mes/': {
      id: '/_authenticated/mes/'
      path: '/mes'
      fullPath: '/mes'
      preLoaderRoute: typeof AuthenticatedMesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/system/user-management': {
      id: '/_authenticated/system/user-management'
      path: '/system/user-management'
      fullPath: '/system/user-management'
      preLoaderRoute: typeof AuthenticatedSystemUserManagementRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/system/test-upload': {
      id: '/_authenticated/system/test-upload'
      path: '/system/test-upload'
      fullPath: '/system/test-upload'
      preLoaderRoute: typeof AuthenticatedSystemTestUploadRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/system/settings': {
      id: '/_authenticated/system/settings'
      path: '/system/settings'
      fullPath: '/system/settings'
      preLoaderRoute: typeof AuthenticatedSystemSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/system/role-management': {
      id: '/_authenticated/system/role-management'
      path: '/system/role-management'
      fullPath: '/system/role-management'
      preLoaderRoute: typeof AuthenticatedSystemRoleManagementRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/system/integrations': {
      id: '/_authenticated/system/integrations'
      path: '/system/integrations'
      fullPath: '/system/integrations'
      preLoaderRoute: typeof AuthenticatedSystemIntegrationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/system/audit-logs': {
      id: '/_authenticated/system/audit-logs'
      path: '/system/audit-logs'
      fullPath: '/system/audit-logs'
      preLoaderRoute: typeof AuthenticatedSystemAuditLogsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/mes/work-orders': {
      id: '/_authenticated/mes/work-orders'
      path: '/mes/work-orders'
      fullPath: '/mes/work-orders'
      preLoaderRoute: typeof AuthenticatedMesWorkOrdersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/mes/trace': {
      id: '/_authenticated/mes/trace'
      path: '/mes/trace'
      fullPath: '/mes/trace'
      preLoaderRoute: typeof AuthenticatedMesTraceRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/mes/routes': {
      id: '/_authenticated/mes/routes'
      path: '/mes/routes'
      fullPath: '/mes/routes'
      preLoaderRoute: typeof AuthenticatedMesRoutesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/mes/route-versions': {
      id: '/_authenticated/mes/route-versions'
      path: '/mes/route-versions'
      fullPath: '/mes/route-versions'
      preLoaderRoute: typeof AuthenticatedMesRouteVersionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/mes/rework-tasks': {
      id: '/_authenticated/mes/rework-tasks'
      path: '/mes/rework-tasks'
      fullPath: '/mes/rework-tasks'
      preLoaderRoute: typeof AuthenticatedMesReworkTasksRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/mes/readiness-exceptions': {
      id: '/_authenticated/mes/readiness-exceptions'
      path: '/mes/readiness-exceptions'
      fullPath: '/mes/readiness-exceptions'
      preLoaderRoute: typeof AuthenticatedMesReadinessExceptionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/mes/readiness-config': {
      id: '/_authenticated/mes/readiness-config'
      path: '/mes/readiness-config'
      fullPath: '/mes/readiness-config'
      preLoaderRoute: typeof AuthenticatedMesReadinessConfigRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/mes/fai': {
      id: '/_authenticated/mes/fai'
      path: '/mes/fai'
      fullPath: '/mes/fai'
      preLoaderRoute: typeof AuthenticatedMesFaiRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/mes/execution': {
      id: '/_authenticated/mes/execution'
      path: '/mes/execution'
      fullPath: '/mes/execution'
      preLoaderRoute: typeof AuthenticatedMesExecutionRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/mes/defects': {
      id: '/_authenticated/mes/defects'
      path: '/mes/defects'
      fullPath: '/mes/defects'
      preLoaderRoute: typeof AuthenticatedMesDefectsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/mes/work-centers/': {
      id: '/_authenticated/mes/work-centers/'
      path: '/mes/work-centers'
      fullPath: '/mes/work-centers'
      preLoaderRoute: typeof AuthenticatedMesWorkCentersIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/mes/runs/': {
      id: '/_authenticated/mes/runs/'
      path: '/mes/runs'
      fullPath: '/mes/runs'
      preLoaderRoute: typeof AuthenticatedMesRunsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/mes/routes/': {
      id: '/_authenticated/mes/routes/'
      path: '/'
      fullPath: '/mes/routes/'
      preLoaderRoute: typeof AuthenticatedMesRoutesIndexRouteImport
      parentRoute: typeof AuthenticatedMesRoutesRoute
    }
    '/_authenticated/mes/oqc/': {
      id: '/_authenticated/mes/oqc/'
      path: '/mes/oqc'
      fullPath: '/mes/oqc'
      preLoaderRoute: typeof AuthenticatedMesOqcIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/mes/materials/': {
      id: '/_authenticated/mes/materials/'
      path: '/mes/materials'
      fullPath: '/mes/materials'
      preLoaderRoute: typeof AuthenticatedMesMaterialsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/mes/loading/': {
      id: '/_authenticated/mes/loading/'
      path: '/mes/loading'
      fullPath: '/mes/loading'
      preLoaderRoute: typeof AuthenticatedMesLoadingIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/mes/data-collection-specs/': {
      id: '/_authenticated/mes/data-collection-specs/'
      path: '/mes/data-collection-specs'
      fullPath: '/mes/data-collection-specs'
      preLoaderRoute: typeof AuthenticatedMesDataCollectionSpecsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/mes/boms/': {
      id: '/_authenticated/mes/boms/'
      path: '/mes/boms'
      fullPath: '/mes/boms'
      preLoaderRoute: typeof AuthenticatedMesBomsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/mes/bake-records/': {
      id: '/_authenticated/mes/bake-records/'
      path: '/mes/bake-records'
      fullPath: '/mes/bake-records'
      preLoaderRoute: typeof AuthenticatedMesBakeRecordsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/mes/runs/$runNo': {
      id: '/_authenticated/mes/runs/$runNo'
      path: '/mes/runs/$runNo'
      fullPath: '/mes/runs/$runNo'
      preLoaderRoute: typeof AuthenticatedMesRunsRunNoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/mes/routes/$routingCode': {
      id: '/_authenticated/mes/routes/$routingCode'
      path: '/$routingCode'
      fullPath: '/mes/routes/$routingCode'
      preLoaderRoute: typeof AuthenticatedMesRoutesRoutingCodeRouteImport
      parentRoute: typeof AuthenticatedMesRoutesRoute
    }
    '/_authenticated/mes/oqc/rules': {
      id: '/_authenticated/mes/oqc/rules'
      path: '/mes/oqc/rules'
      fullPath: '/mes/oqc/rules'
      preLoaderRoute: typeof AuthenticatedMesOqcRulesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/mes/loading/slot-config': {
      id: '/_authenticated/mes/loading/slot-config'
      path: '/mes/loading/slot-config'
      fullPath: '/mes/loading/slot-config'
      preLoaderRoute: typeof AuthenticatedMesLoadingSlotConfigRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/mes/integration/status': {
      id: '/_authenticated/mes/integration/status'
      path: '/mes/integration/status'
      fullPath: '/mes/integration/status'
      preLoaderRoute: typeof AuthenticatedMesIntegrationStatusRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/mes/integration/manual-entry': {
      id: '/_authenticated/mes/integration/manual-entry'
      path: '/mes/integration/manual-entry'
      fullPath: '/mes/integration/manual-entry'
      preLoaderRoute: typeof AuthenticatedMesIntegrationManualEntryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedMesRoutesRouteChildren {
  AuthenticatedMesRoutesRoutingCodeRoute: typeof AuthenticatedMesRoutesRoutingCodeRoute
  AuthenticatedMesRoutesIndexRoute: typeof AuthenticatedMesRoutesIndexRoute
}

const AuthenticatedMesRoutesRouteChildren: AuthenticatedMesRoutesRouteChildren =
  {
    AuthenticatedMesRoutesRoutingCodeRoute:
      AuthenticatedMesRoutesRoutingCodeRoute,
    AuthenticatedMesRoutesIndexRoute: AuthenticatedMesRoutesIndexRoute,
  }

const AuthenticatedMesRoutesRouteWithChildren =
  AuthenticatedMesRoutesRoute._addFileChildren(
    AuthenticatedMesRoutesRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedMesDefectsRoute: typeof AuthenticatedMesDefectsRoute
  AuthenticatedMesExecutionRoute: typeof AuthenticatedMesExecutionRoute
  AuthenticatedMesFaiRoute: typeof AuthenticatedMesFaiRoute
  AuthenticatedMesReadinessConfigRoute: typeof AuthenticatedMesReadinessConfigRoute
  AuthenticatedMesReadinessExceptionsRoute: typeof AuthenticatedMesReadinessExceptionsRoute
  AuthenticatedMesReworkTasksRoute: typeof AuthenticatedMesReworkTasksRoute
  AuthenticatedMesRouteVersionsRoute: typeof AuthenticatedMesRouteVersionsRoute
  AuthenticatedMesRoutesRoute: typeof AuthenticatedMesRoutesRouteWithChildren
  AuthenticatedMesTraceRoute: typeof AuthenticatedMesTraceRoute
  AuthenticatedMesWorkOrdersRoute: typeof AuthenticatedMesWorkOrdersRoute
  AuthenticatedSystemAuditLogsRoute: typeof AuthenticatedSystemAuditLogsRoute
  AuthenticatedSystemIntegrationsRoute: typeof AuthenticatedSystemIntegrationsRoute
  AuthenticatedSystemRoleManagementRoute: typeof AuthenticatedSystemRoleManagementRoute
  AuthenticatedSystemSettingsRoute: typeof AuthenticatedSystemSettingsRoute
  AuthenticatedSystemTestUploadRoute: typeof AuthenticatedSystemTestUploadRoute
  AuthenticatedSystemUserManagementRoute: typeof AuthenticatedSystemUserManagementRoute
  AuthenticatedMesIndexRoute: typeof AuthenticatedMesIndexRoute
  AuthenticatedSystemIndexRoute: typeof AuthenticatedSystemIndexRoute
  AuthenticatedMesIntegrationManualEntryRoute: typeof AuthenticatedMesIntegrationManualEntryRoute
  AuthenticatedMesIntegrationStatusRoute: typeof AuthenticatedMesIntegrationStatusRoute
  AuthenticatedMesLoadingSlotConfigRoute: typeof AuthenticatedMesLoadingSlotConfigRoute
  AuthenticatedMesOqcRulesRoute: typeof AuthenticatedMesOqcRulesRoute
  AuthenticatedMesRunsRunNoRoute: typeof AuthenticatedMesRunsRunNoRoute
  AuthenticatedMesBakeRecordsIndexRoute: typeof AuthenticatedMesBakeRecordsIndexRoute
  AuthenticatedMesBomsIndexRoute: typeof AuthenticatedMesBomsIndexRoute
  AuthenticatedMesDataCollectionSpecsIndexRoute: typeof AuthenticatedMesDataCollectionSpecsIndexRoute
  AuthenticatedMesLoadingIndexRoute: typeof AuthenticatedMesLoadingIndexRoute
  AuthenticatedMesMaterialsIndexRoute: typeof AuthenticatedMesMaterialsIndexRoute
  AuthenticatedMesOqcIndexRoute: typeof AuthenticatedMesOqcIndexRoute
  AuthenticatedMesRunsIndexRoute: typeof AuthenticatedMesRunsIndexRoute
  AuthenticatedMesWorkCentersIndexRoute: typeof AuthenticatedMesWorkCentersIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedMesDefectsRoute: AuthenticatedMesDefectsRoute,
  AuthenticatedMesExecutionRoute: AuthenticatedMesExecutionRoute,
  AuthenticatedMesFaiRoute: AuthenticatedMesFaiRoute,
  AuthenticatedMesReadinessConfigRoute: AuthenticatedMesReadinessConfigRoute,
  AuthenticatedMesReadinessExceptionsRoute:
    AuthenticatedMesReadinessExceptionsRoute,
  AuthenticatedMesReworkTasksRoute: AuthenticatedMesReworkTasksRoute,
  AuthenticatedMesRouteVersionsRoute: AuthenticatedMesRouteVersionsRoute,
  AuthenticatedMesRoutesRoute: AuthenticatedMesRoutesRouteWithChildren,
  AuthenticatedMesTraceRoute: AuthenticatedMesTraceRoute,
  AuthenticatedMesWorkOrdersRoute: AuthenticatedMesWorkOrdersRoute,
  AuthenticatedSystemAuditLogsRoute: AuthenticatedSystemAuditLogsRoute,
  AuthenticatedSystemIntegrationsRoute: AuthenticatedSystemIntegrationsRoute,
  AuthenticatedSystemRoleManagementRoute:
    AuthenticatedSystemRoleManagementRoute,
  AuthenticatedSystemSettingsRoute: AuthenticatedSystemSettingsRoute,
  AuthenticatedSystemTestUploadRoute: AuthenticatedSystemTestUploadRoute,
  AuthenticatedSystemUserManagementRoute:
    AuthenticatedSystemUserManagementRoute,
  AuthenticatedMesIndexRoute: AuthenticatedMesIndexRoute,
  AuthenticatedSystemIndexRoute: AuthenticatedSystemIndexRoute,
  AuthenticatedMesIntegrationManualEntryRoute:
    AuthenticatedMesIntegrationManualEntryRoute,
  AuthenticatedMesIntegrationStatusRoute:
    AuthenticatedMesIntegrationStatusRoute,
  AuthenticatedMesLoadingSlotConfigRoute:
    AuthenticatedMesLoadingSlotConfigRoute,
  AuthenticatedMesOqcRulesRoute: AuthenticatedMesOqcRulesRoute,
  AuthenticatedMesRunsRunNoRoute: AuthenticatedMesRunsRunNoRoute,
  AuthenticatedMesBakeRecordsIndexRoute: AuthenticatedMesBakeRecordsIndexRoute,
  AuthenticatedMesBomsIndexRoute: AuthenticatedMesBomsIndexRoute,
  AuthenticatedMesDataCollectionSpecsIndexRoute:
    AuthenticatedMesDataCollectionSpecsIndexRoute,
  AuthenticatedMesLoadingIndexRoute: AuthenticatedMesLoadingIndexRoute,
  AuthenticatedMesMaterialsIndexRoute: AuthenticatedMesMaterialsIndexRoute,
  AuthenticatedMesOqcIndexRoute: AuthenticatedMesOqcIndexRoute,
  AuthenticatedMesRunsIndexRoute: AuthenticatedMesRunsIndexRoute,
  AuthenticatedMesWorkCentersIndexRoute: AuthenticatedMesWorkCentersIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
