/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedSystemIndexRouteImport } from './routes/_authenticated/system/index'
import { Route as AuthenticatedInstrumentsIndexRouteImport } from './routes/_authenticated/instruments/index'
import { Route as AuthenticatedCalibrationsIndexRouteImport } from './routes/_authenticated/calibrations/index'
import { Route as AuthenticatedSystemUserManagementRouteImport } from './routes/_authenticated/system/user-management'
import { Route as AuthenticatedSystemSettingsRouteImport } from './routes/_authenticated/system/settings'
import { Route as AuthenticatedInstrumentsInstrumentIdRouteImport } from './routes/_authenticated/instruments/$instrumentId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSystemIndexRoute =
  AuthenticatedSystemIndexRouteImport.update({
    id: '/system/',
    path: '/system/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInstrumentsIndexRoute =
  AuthenticatedInstrumentsIndexRouteImport.update({
    id: '/instruments/',
    path: '/instruments/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCalibrationsIndexRoute =
  AuthenticatedCalibrationsIndexRouteImport.update({
    id: '/calibrations/',
    path: '/calibrations/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSystemUserManagementRoute =
  AuthenticatedSystemUserManagementRouteImport.update({
    id: '/system/user-management',
    path: '/system/user-management',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSystemSettingsRoute =
  AuthenticatedSystemSettingsRouteImport.update({
    id: '/system/settings',
    path: '/system/settings',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInstrumentsInstrumentIdRoute =
  AuthenticatedInstrumentsInstrumentIdRouteImport.update({
    id: '/instruments/$instrumentId',
    path: '/instruments/$instrumentId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/': typeof AuthenticatedIndexRoute
  '/instruments/$instrumentId': typeof AuthenticatedInstrumentsInstrumentIdRoute
  '/system/settings': typeof AuthenticatedSystemSettingsRoute
  '/system/user-management': typeof AuthenticatedSystemUserManagementRoute
  '/calibrations': typeof AuthenticatedCalibrationsIndexRoute
  '/instruments': typeof AuthenticatedInstrumentsIndexRoute
  '/system': typeof AuthenticatedSystemIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/': typeof AuthenticatedIndexRoute
  '/instruments/$instrumentId': typeof AuthenticatedInstrumentsInstrumentIdRoute
  '/system/settings': typeof AuthenticatedSystemSettingsRoute
  '/system/user-management': typeof AuthenticatedSystemUserManagementRoute
  '/calibrations': typeof AuthenticatedCalibrationsIndexRoute
  '/instruments': typeof AuthenticatedInstrumentsIndexRoute
  '/system': typeof AuthenticatedSystemIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/instruments/$instrumentId': typeof AuthenticatedInstrumentsInstrumentIdRoute
  '/_authenticated/system/settings': typeof AuthenticatedSystemSettingsRoute
  '/_authenticated/system/user-management': typeof AuthenticatedSystemUserManagementRoute
  '/_authenticated/calibrations/': typeof AuthenticatedCalibrationsIndexRoute
  '/_authenticated/instruments/': typeof AuthenticatedInstrumentsIndexRoute
  '/_authenticated/system/': typeof AuthenticatedSystemIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/notifications'
    | '/profile'
    | '/'
    | '/instruments/$instrumentId'
    | '/system/settings'
    | '/system/user-management'
    | '/calibrations'
    | '/instruments'
    | '/system'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/notifications'
    | '/profile'
    | '/'
    | '/instruments/$instrumentId'
    | '/system/settings'
    | '/system/user-management'
    | '/calibrations'
    | '/instruments'
    | '/system'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/notifications'
    | '/_authenticated/profile'
    | '/_authenticated/'
    | '/_authenticated/instruments/$instrumentId'
    | '/_authenticated/system/settings'
    | '/_authenticated/system/user-management'
    | '/_authenticated/calibrations/'
    | '/_authenticated/instruments/'
    | '/_authenticated/system/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/system/': {
      id: '/_authenticated/system/'
      path: '/system'
      fullPath: '/system'
      preLoaderRoute: typeof AuthenticatedSystemIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/instruments/': {
      id: '/_authenticated/instruments/'
      path: '/instruments'
      fullPath: '/instruments'
      preLoaderRoute: typeof AuthenticatedInstrumentsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/calibrations/': {
      id: '/_authenticated/calibrations/'
      path: '/calibrations'
      fullPath: '/calibrations'
      preLoaderRoute: typeof AuthenticatedCalibrationsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/system/user-management': {
      id: '/_authenticated/system/user-management'
      path: '/system/user-management'
      fullPath: '/system/user-management'
      preLoaderRoute: typeof AuthenticatedSystemUserManagementRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/system/settings': {
      id: '/_authenticated/system/settings'
      path: '/system/settings'
      fullPath: '/system/settings'
      preLoaderRoute: typeof AuthenticatedSystemSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/instruments/$instrumentId': {
      id: '/_authenticated/instruments/$instrumentId'
      path: '/instruments/$instrumentId'
      fullPath: '/instruments/$instrumentId'
      preLoaderRoute: typeof AuthenticatedInstrumentsInstrumentIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedInstrumentsInstrumentIdRoute: typeof AuthenticatedInstrumentsInstrumentIdRoute
  AuthenticatedSystemSettingsRoute: typeof AuthenticatedSystemSettingsRoute
  AuthenticatedSystemUserManagementRoute: typeof AuthenticatedSystemUserManagementRoute
  AuthenticatedCalibrationsIndexRoute: typeof AuthenticatedCalibrationsIndexRoute
  AuthenticatedInstrumentsIndexRoute: typeof AuthenticatedInstrumentsIndexRoute
  AuthenticatedSystemIndexRoute: typeof AuthenticatedSystemIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedInstrumentsInstrumentIdRoute:
    AuthenticatedInstrumentsInstrumentIdRoute,
  AuthenticatedSystemSettingsRoute: AuthenticatedSystemSettingsRoute,
  AuthenticatedSystemUserManagementRoute:
    AuthenticatedSystemUserManagementRoute,
  AuthenticatedCalibrationsIndexRoute: AuthenticatedCalibrationsIndexRoute,
  AuthenticatedInstrumentsIndexRoute: AuthenticatedInstrumentsIndexRoute,
  AuthenticatedSystemIndexRoute: AuthenticatedSystemIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
