export const MES_ERROR_MESSAGES = {
	RUN_NOT_FOUND: "批次不存在",
	RUN_NOT_AUTHORIZED: "批次未授权，请先完成授权",
	RUN_STATUS_INVALID: "批次状态不支持当前操作",
	RUN_LINE_NOT_SET: "批次未指定产线",
	RUN_WORK_ORDER_MISMATCH: "批次与工单不匹配",
	WORK_ORDER_NO_ROUTING: "工单未绑定可执行路由",
	UNIT_NOT_FOUND: "未找到该单件",
	UNIT_ALREADY_IN_STATION: "单件已在站内",
	UNIT_ALREADY_DONE: "单件已完成",
	UNIT_OUT_FAILED: "单件已判定失败，禁止继续进站",
	UNIT_SCRAPPED: "单件已报废，禁止继续进站",
	STEP_MISMATCH: "当前工序不匹配，请按顺序执行",
	STATION_MISMATCH: "工位与当前步骤不匹配",
	STATION_LINE_MISMATCH: "工位不属于该产线",
	STATION_NOT_FOUND: "未找到工位信息",
	ROUTE_VERSION_NOT_READY: "路由版本未就绪",
	ROUTING_EMPTY: "路由步骤为空",
	READINESS_CHECK_FAILED: "就绪检查未通过，请处理全部失败项或豁免后再授权",
	RUN_NOT_READY: "批次状态不支持授权操作",
	FAI_NOT_FOUND: "未找到首件检验记录",
	FAI_NOT_PASSED: "首件检验未通过，请先完成 FAI 检验",
	FAI_TRIAL_STEP_NOT_ALLOWED: "首件试产仅允许在指定工序执行",
	FAI_TRIAL_LIMIT_REACHED: "首件试产数量已达上限",
	FAI_UNITS_REQUIRED: "请先生成首件试产单件",
	OQC_REQUIRED: "需要先完成出货检验",
	DATA_SPEC_NOT_FOUND: "采集项配置不存在",
	REQUIRED_DATA_MISSING: "必填采集项未填写",
	DATA_VALUE_INVALID: "采集数据格式不正确",
	SLOT_NOT_FOUND: "站位不存在",
	SLOT_LOCKED: "站位已锁定，请先解锁",
	SLOT_ALREADY_LOADED: "站位已上料，请使用换料",
	SLOT_NOT_LOADED: "站位未上料，请先扫码上料",
	SLOT_EXPECTATION_MISSING: "站位表未加载，请先加载站位表",
	SLOT_MAPPING_MISSING: "站位映射缺失，请完善物料映射",
	FEEDER_SLOTS_NOT_FOUND: "产线未配置站位",
	LOADING_ALREADY_STARTED: "该批次已开始上料",
	MATERIAL_LOT_NOT_FOUND: "未找到物料批次",
	MATERIAL_LOT_AMBIGUOUS: "物料批次不唯一，请补充完整条码",
	ITEM_NOT_FOUND: "检查项不存在",
	ITEM_NOT_FAILED: "仅允许豁免失败项",
	REASON_REQUIRED: "请输入原因",
	OPERATOR_REQUIRED: "需要操作员信息",
	UNAUTHORIZED: "未登录或无权限",
	FORBIDDEN: "没有权限执行该操作",
	NETWORK_ERROR: "网络异常，请稍后重试",
	NO_DATA: "未获取到返回数据",
	BUSINESS_ERROR: "业务处理失败",
	UNKNOWN_ERROR: "未知错误",
} as const;

export type MesErrorCode = keyof typeof MES_ERROR_MESSAGES;

export const getMesErrorMessage = (code?: string | null) => {
	if (!code) return undefined;
	return (MES_ERROR_MESSAGES as Record<string, string>)[code];
};
