import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";

const usage = (): never => {
	console.error("Usage: bun scripts/mes-triage-note.ts --topic <topic>");
	process.exit(1);
};

const parseArgs = (argv: string[]) => {
	const args = argv.slice(2);
	let topic: string | null = null;

	for (let i = 0; i < args.length; i += 1) {
		const arg = args[i];
		if (arg === "--help" || arg === "-h") usage();
		if (arg === "--topic") {
			topic = args[i + 1] ?? null;
			i += 1;
			continue;
		}
		usage();
	}

	if (!topic) usage();
	return { topic };
};

const runConversationNew = (topic: string): string => {
	const proc = Bun.spawnSync(["bun", "scripts/conversation-new.ts", topic], {
		stdout: "pipe",
		stderr: "pipe",
	});
	const stdout = new TextDecoder().decode(proc.stdout ?? new Uint8Array()).trim();
	const stderr = new TextDecoder().decode(proc.stderr ?? new Uint8Array()).trim();
	if (proc.exitCode !== 0) throw new Error(stderr || stdout || `conversation-new failed (${proc.exitCode})`);
	if (!stdout) throw new Error("conversation-new returned empty path");
	return stdout;
};

const ensureDir = (dirPath: string) => {
	mkdirSync(dirPath, { recursive: true });
};

const main = () => {
	const repoRoot = process.cwd();
	const { topic } = parseArgs(process.argv);

	const outputsDir = process.env.WORKFLOW_OUTPUTS_DIR
		? path.resolve(repoRoot, process.env.WORKFLOW_OUTPUTS_DIR)
		: null;
	if (!outputsDir) throw new Error("Missing WORKFLOW_OUTPUTS_DIR (run via workflow-run)");

	const triagePath = path.join(outputsDir, "triage.md");
	const triage = readFileSync(triagePath, "utf8").trimEnd();

	const outPath = runConversationNew(topic);
	const relPlan = "domain_docs/mes/plan/phase3_tasks.md";

	const content = [
		`# ${topic}`,
		"",
		"## Context",
		`- Generated by \`bun scripts/workflow-run.ts agent_workflows/mes-triage.json\``,
		`- Plan source: \`${relPlan}\``,
		"",
		"## Decisions",
		"- (none yet; waiting for selection)",
		"",
		"## Plan",
		triage,
		"",
		"## Open Questions",
		"- Pick one candidate; then we switch to `mes-implement` and land code slice-by-slice.",
		"",
		"## References",
		`- \`${relPlan}\``,
		"- `scripts/mes-triage-render.ts`",
		"- `scripts/workflow-run.ts`",
		"- `agent_workflows/mes-triage.json`",
		"",
	].join("\n");

	ensureDir(path.dirname(outPath));
	writeFileSync(outPath, content, "utf8");

	console.log(outPath);
};

main();

