import path from "node:path";

type EmbeddedWebAsset = {
	contentType: string;
	base64: string;
	immutable?: boolean;
};

const contentTypeByExt: Record<string, string> = {
	".html": "text/html; charset=utf-8",
	".js": "text/javascript; charset=utf-8",
	".css": "text/css; charset=utf-8",
	".json": "application/json; charset=utf-8",
	".map": "application/json; charset=utf-8",
	".svg": "image/svg+xml",
	".png": "image/png",
	".jpg": "image/jpeg",
	".jpeg": "image/jpeg",
	".ico": "image/x-icon",
	".txt": "text/plain; charset=utf-8",
	".woff2": "font/woff2",
	".woff": "font/woff",
	".ttf": "font/ttf",
	".eot": "application/vnd.ms-fontobject",
	".wasm": "application/wasm",
};

const walk = async (dir: string): Promise<string[]> => {
	const entries: string[] = [];
	for await (const entry of new Bun.Glob("**/*").scan({ cwd: dir, onlyFiles: true })) {
		entries.push(path.join(dir, entry));
	}
	return entries;
};

const toPosix = (p: string) => p.replaceAll(path.sep, "/");

const main = async () => {
	const distDir = path.resolve(import.meta.dir, "../../web/dist");
	const outFile = path.resolve(import.meta.dir, "../src/web/embedded-assets.generated.ts");

	if (!(await Bun.file(path.join(distDir, "index.html")).exists())) {
		throw new Error(`Web dist not found at ${distDir}. Run \`bun run --filter web build\` first.`);
	}

	const files = (await walk(distDir)).sort((a, b) => a.localeCompare(b));
	const assets: Record<string, EmbeddedWebAsset> = {};

	for (const filePath of files) {
		const rel = toPosix(path.relative(distDir, filePath));
		const urlPath = `/${rel}`;

		const ext = path.extname(filePath).toLowerCase();
		const contentType = contentTypeByExt[ext] ?? "application/octet-stream";
		const immutable = urlPath.startsWith("/assets/") && !urlPath.endsWith(".map") && urlPath !== "/index.html";

		const bytes = await Bun.file(filePath).arrayBuffer();
		const base64 = Buffer.from(bytes).toString("base64");

		assets[urlPath] = { contentType, base64, ...(immutable ? { immutable: true } : null) };
	}

	if (!assets["/index.html"]) {
		throw new Error(`Missing ${path.join(distDir, "index.html")}; Vite build looks incomplete.`);
	}

	const header = [
		"// This file is generated by `bun run gen:web-embed`.",
		"// Do not edit manually.",
		'import type { EmbeddedWebAsset } from "./embedded-assets";',
		"",
	].join("\n");

	const lines: string[] = [];
	lines.push(`${header}export const embeddedWebAssets: Record<string, EmbeddedWebAsset> = {`);
	for (const [key, value] of Object.entries(assets)) {
		lines.push(
			`\t${JSON.stringify(key)}: { contentType: ${JSON.stringify(value.contentType)}, base64: ${JSON.stringify(value.base64)}${
				value.immutable ? ", immutable: true" : ""
			} },`,
		);
	}
	lines.push("};\n");

	await Bun.write(outFile, lines.join("\n"));
	console.log(`[gen:web-embed] Wrote ${Object.keys(assets).length} assets to ${outFile}`);
};

await main();
